# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ftl < Formula
  desc "FTL - Towards a 𝝺-calculus for large-scale systems"
  homepage "https://github.com/TBD54566975/ftl"
  version "0.276.3"

  on_macos do
    on_intel do
      url "https://github.com/TBD54566975/ftl/releases/download/v0.276.3/ftl-0.276.3.darwin-amd64.tar.gz"
      sha256 "55cf0591809c796ec5079103e80b6b56e892dcb437976cb63d474a4a925d1b19"

      def install
        bin.install "ftl"
      end
    end
    on_arm do
      url "https://github.com/TBD54566975/ftl/releases/download/v0.276.3/ftl-0.276.3.darwin-arm64.tar.gz"
      sha256 "cdafcaf6e158b74154ba9893f1f579f735a98fb9a588b9e793d10be6c7e6699b"

      def install
        bin.install "ftl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TBD54566975/ftl/releases/download/v0.276.3/ftl-0.276.3.linux-amd64.tar.gz"
        sha256 "79d6f943a2df3a654de0579bdf828d5bf2467ce33c36349d0f8af43cf580bf31"

        def install
          bin.install "ftl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TBD54566975/ftl/releases/download/v0.276.3/ftl-0.276.3.linux-arm64.tar.gz"
        sha256 "1906effb5f7ac036957882bf68746dd3daff3b96cd0b5f29b82c09f609b5edff"

        def install
          bin.install "ftl"
        end
      end
    end
  end
end
