# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ftl < Formula
  desc "FTL - Towards a 𝝺-calculus for large-scale systems"
  homepage "https://github.com/TBD54566975/ftl"
  version "0.282.2"

  on_macos do
    on_intel do
      url "https://github.com/TBD54566975/ftl/releases/download/v0.282.2/ftl-0.282.2.darwin-amd64.tar.gz"
      sha256 "03d7617a562e188fb98c5fc4d05f93a97fa8d0bfe46b36fc80d588f5a27bf9ef"

      def install
        bin.install "ftl"
      end
    end
    on_arm do
      url "https://github.com/TBD54566975/ftl/releases/download/v0.282.2/ftl-0.282.2.darwin-arm64.tar.gz"
      sha256 "730b911bce323122f3355621d0388e77334a5bec61ec730326f94b4845f53836"

      def install
        bin.install "ftl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TBD54566975/ftl/releases/download/v0.282.2/ftl-0.282.2.linux-amd64.tar.gz"
        sha256 "695331839bb2fe4aeaaeb8929bbfa1a2067f064a2aae75d9eb53bb80a7ec2ec7"

        def install
          bin.install "ftl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TBD54566975/ftl/releases/download/v0.282.2/ftl-0.282.2.linux-arm64.tar.gz"
        sha256 "bf2319964de1030d557dc2ce7f092d1cfaba1da9f64cac654528ac4b80fe1ebc"

        def install
          bin.install "ftl"
        end
      end
    end
  end
end
